version: '3.8'

services:
  app:
    build: .
    container_name: paw12-php-runtime
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - paw-internal

  web:
    image: nginx:latest
    container_name: paw12-nginx-web
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - paw-internal
      - paw-public

  db:
    image: mysql:8.0
    container_name: paw12-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3307:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - paw-internal

networks:
  paw-internal:
    internal: true
  paw-public:
    driver: bridge
